# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dunfermline West Baptist Church
email: enquiries@dunfermlinewest.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Baptist Church
timezone: Europe/London
baseurl: "" # the subpath of your site, e.g. /blog
#url: http://127.0.0.1:80/
logo: /assets/img/logo.png
url: "http://dunfermlinewest.org" # the base hostname & protocol for your site
#plugins:
#    - jekyll-admin


# Social media profiles - feel free to add more here
#twitter_username: SBootstrap
#github_username:  BlackrockDigital
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Dunfermline West Baptist Church
address_city: Chalmers Street
address_state: Dunfermline
address_zip: KY12 8DG

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true